
-- DO NOT EDIT THIS FILE, THIS IS THE TEMPLATE
-- If you cannot use the in-game menu and need to edit the config by hand,
-- the config file can be found at `Daedalic Entertainment GmbH/Barotrauma/ModConfigs/EnhancedImmersion.json`

local config = {}

-- values are in percentage
config.CameraZoom = 50
config.PeriscopeOffset = 50
config.AimOffset = 100

-- host/serverside only
-- if true, make clients use the same configuration as the server
config.SyncConfig = true

return config
